services:
  postgres:
    image: 'postgres:alpine3.17'
    environment:
      - 'POSTGRES_DB=multitenancy_car'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
