--CREATE ROLE JOHNDOE_ROLE LOGIN PASSWORD 'JOHNDOEPASSWORD';
--CREATE SCHEMA IF NOT EXISTS JOHNDOE AUTHORIZATION JOHNDOE_ROLE;
--GRANT USAGE ON SCHEMA JOHNDOE TO JOHNDOE_ROLE;
-- uncomment code above when first running the app
CREATE TABLE IF NOT EXISTS JOHNDOE.CARS(id VARCHAR(20) primary key, brand VARCHAR(20), color VARCHAR(30));
INSERT INTO JOHNDOE.CARS values ('MAZDA_1', 'MAZDA', 'RED');

--CREATE ROLE ANNADOE_ROLE LOGIN PASSWORD 'ANNADOEPASSWORD';
--CREATE SCHEMA IF NOT EXISTS ANNADOE AUTHORIZATION ANNADOE_ROLE;
--GRANT USAGE ON SCHEMA ANNADOE TO ANNADOE_ROLE;
-- uncomment code above when first running the app
CREATE TABLE IF NOT EXISTS ANNADOE.CARS(id VARCHAR(20) primary key, brand VARCHAR(20), color VARCHAR(30));
INSERT INTO ANNADOE.CARS values ('FORD_1', 'BMW', 'WHITE'), ('FORD_2', 'BMW', 'BLUE');



